### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by foobit** [benpollarduk/BP.AdventureFramework#50]
It would be great to have _localization_ support for multiple languages. Hardcoded strings would use some lut _(look up table)_ to get the correct locale string.

**Comment by benpollarduk** [comment]
It's a good call, I've given it some thought and it's not quite as easy. A lot of the text is generated and is state specific - for example - "You have **a** banana, **a** peach and **an** apple", so a bit of work is required beyond implementing a LUT with little gain currently.
