### ISSUE TITLE
Emoji/ extended Unicode support.

### ISSUE THREAD

**Issue by foobit** [benpollarduk/BP.AdventureFramework#52]
Most terminals support Emoji characters. Emoji is a great way to have graphics in text games.
🪦 gravestone
🪧 sign
⛏️ pickaxe
⚔️ sword
🏰 castle
🏹 bow
🐉 dragon
🧙 wizard

[Wikipedia Unicode blocks](https://en.wikipedia.org/wiki/Emoji#Unicode_blocks)

### Background
> On Windows platforms `cmd.exe` has terrible text output support. However, the new Windows Terminal `wt.exe` has excellent support for formatting.

```c#
// Enable UTF8 output to support emoji (required to display the below emoji correctly)
Console.OutputEncoding = Encoding.UTF8;

// Displays a smiley emoji 😀
Console.Write("\U0001F600");
```

### Markup
Having a string extension to convert human readable markup to emoji. Could be a good feature.
```c#
// dagger🗡️
Console.WriteLine(":dagger:".Markup());
```

**Comment by benpollarduk** [comment]
Emoji through unicode should be supported, asset names or descriptions should just be specified as unicode to render the emoji. There's so many characters I think building in support is cumbersome, however users could add the extensions for the emoji they use when they write games.
